# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "react-storefront"
client_id = "47884a72db7ddd78c95a77a29985b5fd"
application_url = "https://police-drawn-reads-xi.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://police-drawn-reads-xi.trycloudflare.com/auth/callback",
  "https://police-drawn-reads-xi.trycloudflare.com/auth/shopify/callback",
  "https://police-drawn-reads-xi.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-69a1c8bb.myshopify.com"
